// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbU2dwro7R-ZzgtuudtuI5Pr1D0RdKvvU',
    appId: '1:376574877941:web:8ad6373d15d2d511b425bc',
    messagingSenderId: '376574877941',
    projectId: 'expense-monitor-57193',
    authDomain: 'expense-monitor-57193.firebaseapp.com',
    storageBucket: 'expense-monitor-57193.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowOyqTneYW97IZI7Aa940KsNBnPjk-Y8',
    appId: '1:376574877941:android:04b54859be15612ab425bc',
    messagingSenderId: '376574877941',
    projectId: 'expense-monitor-57193',
    storageBucket: 'expense-monitor-57193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKjWxgfJaLL-FBmGbs86pNbxv0aYwtOA',
    appId: '1:376574877941:ios:b30cb07dc83e3abbb425bc',
    messagingSenderId: '376574877941',
    projectId: 'expense-monitor-57193',
    storageBucket: 'expense-monitor-57193.appspot.com',
    iosBundleId: 'com.example.expenseMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKjWxgfJaLL-FBmGbs86pNbxv0aYwtOA',
    appId: '1:376574877941:ios:b30cb07dc83e3abbb425bc',
    messagingSenderId: '376574877941',
    projectId: 'expense-monitor-57193',
    storageBucket: 'expense-monitor-57193.appspot.com',
    iosBundleId: 'com.example.expenseMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbU2dwro7R-ZzgtuudtuI5Pr1D0RdKvvU',
    appId: '1:376574877941:web:a2af631dfbd52665b425bc',
    messagingSenderId: '376574877941',
    projectId: 'expense-monitor-57193',
    authDomain: 'expense-monitor-57193.firebaseapp.com',
    storageBucket: 'expense-monitor-57193.appspot.com',
  );
}
